name: CI - Build and Test Spring Boot App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v3

    - name: ☕ Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: 🔓 Make mvnw executable
      run: chmod +x ./mvnw

    - name: 📦 Build with Maven Wrapper
      run: ./mvnw clean install

    - name: ✅ Run Tests
      run: ./mvnw test -Dspring.profiles.active=test
